//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnglishPremierLeagueApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transfer
    {
        public int Id { get; set; }
        public int PlayerId { get; set; }
        public string Status { get; set; }
        public decimal Fee { get; set; }
        public int FromId { get; set; }
        public int ToId { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Team TeamTo { get; set; }
        public virtual Team TeamFrom { get; set; }
    }
}
